# Generated by Django 5.2.4 on 2026-09-07 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_site_settings', models.BooleanField(default=False, verbose_name='Sayt sozlamalari')),
                ('can_edit_home_content', models.BooleanField(default=False, verbose_name='Bosh sahifa kontenti')),
                ('can_edit_leaders', models.BooleanField(default=False, verbose_name='Rahbariyat')),
                ('can_edit_announcements', models.BooleanField(default=False, verbose_name="E'lonlar (Announcement)")),
                ('can_edit_korxona_ustavi', models.BooleanField(default=False, verbose_name='Korxona ustavi')),
                ('can_edit_tashkiliy_tuzilma', models.BooleanField(default=False, verbose_name='Tashkiliy tuzilma')),
                ('can_edit_katalog', models.BooleanField(default=False, verbose_name='Katalog')),
                ('can_edit_nomenklatura', models.BooleanField(default=False, verbose_name='Nomenklatura')),
                ('can_edit_narx_navo', models.BooleanField(default=False, verbose_name='Narx-navo')),
                ('can_edit_vacancies', models.BooleanField(default=False, verbose_name="Bo'sh ish o'rinlari")),
                ('can_edit_filiallar', models.BooleanField(default=False, verbose_name='Filiallar')),
                ('can_edit_contact', models.BooleanField(default=False, verbose_name='Qayta aloqa')),
                ('can_edit_elonlar', models.BooleanField(default=False, verbose_name="E'lonlar (product)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin profil',
                'verbose_name_plural': 'Admin profillar',
            },
        ),
    ]
