"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.10.
Xavfsizlik uchun barcha maxfiy ma'lumotlar .env faylida saqlanadi.
"""

import os
from datetime import timedelta
from pathlib import Path

from environs import Env

env = Env()
env.read_env()

# ─────────────────────────────────────────────────────────
# YO'L SOZLAMALARI
# ─────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────
# ASOSIY XAVFSIZLIK SOZLAMALARI
# ─────────────────────────────────────────────────────────

# SECRET_KEY majburiy ravishda .env dan o'qiladi (hardcoded emas!)
SECRET_KEY = env.str("SECRET_KEY")

# DEBUG faqat .env da True bo'lsa True, aks holda False
DEBUG = env.bool("DEBUG", default=False)

# ALLOWED_HOSTS .env dan vergul bilan ajratilgan ro'yxat
_raw_hosts = env.str("ALLOWED_HOSTS", default="localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(",") if h.strip()]

# ─────────────────────────────────────────────────────────
# CSRF VA CORS SOZLAMALARI
# ─────────────────────────────────────────────────────────
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

# CORS: Faqat ro'yxatdagi domenlarga ruxsat (CORS_ALLOW_ALL_ORIGINS = False!)
_raw_cors = env.str(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000"
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _raw_cors.split(",") if o.strip()]
CORS_ALLOW_ALL_ORIGINS = False  # Xavfsizlik: hech qachon True qilmang
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ─────────────────────────────────────────────────────────
# AUTENTIFIKATSIYA BACKEND
# ─────────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'accounts.backends.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# ─────────────────────────────────────────────────────────
# ILOVALAR
# ─────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'uzyol',
    'accounts',
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Token blacklisting (logout uchun)
    'corsheaders',
    'drf_extra_fields',
]

# ─────────────────────────────────────────────────────────
# MIDDLEWARE
# ─────────────────────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ─────────────────────────────────────────────────────────
# XAVFSIZLIK HEADERLARI (Production uchun muhim)
# ─────────────────────────────────────────────────────────
if not DEBUG:
    # HTTPS orqali ulanishni majburlash
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS: Brauzerga faqat HTTPS ishlatishni buyuradi (1 yil)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie xavfsizligi (production)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Cookie sozlamalari (dev va prod uchun ham)
SESSION_COOKIE_HTTPONLY = True    # JavaScript'dan cookie'ga kirish imkonsiz
CSRF_COOKIE_HTTPONLY = False      # Frontend CSRF token olishi uchun
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF hujumiga qarshi

# Kontent turini sniffing'dan himoya
SECURE_CONTENT_TYPE_NOSNIFF = True

# XSS filtri
SECURE_BROWSER_XSS_FILTER = True

# Clickjacking himoyasi
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Referrer policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ─────────────────────────────────────────────────────────
# URL VA TEMPLATE SOZLAMALARI
# ─────────────────────────────────────────────────────────
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ─────────────────────────────────────────────────────────
# MA'LUMOTLAR BAZASI
# ─────────────────────────────────────────────────────────
# DB_HOST .env da berilgan bo'lsa → PostgreSQL, aks holda SQLite (local dev)
_db_host = env.str('DB_HOST', default='')

if _db_host:
    # Production / Docker: PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env.str('DB_NAME'),
            'USER': env.str('DB_USER'),
            'PASSWORD': env.str('DB_PASSWORD'),
            'HOST': _db_host,
            'PORT': env.str('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 60,  # Connection pooling
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Local dev: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ─────────────────────────────────────────────────────────
# PAROL VALIDATSIYASI
# ─────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # Kamida 8 ta belgi (avval 4 edi - xavfli!)
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ─────────────────────────────────────────────────────────
# SWAGGER API HUJJATLARI
# ─────────────────────────────────────────────────────────
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        }
    },
    "USE_SESSION_AUTH": False,
    "VALIDATOR_URL": None,
}

# ─────────────────────────────────────────────────────────
# XALQAROLASHTIRISH
# ─────────────────────────────────────────────────────────
LANGUAGE_CODE = 'uz'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True

# ─────────────────────────────────────────────────────────
# STATIK VA MEDIA FAYLLAR
# ─────────────────────────────────────────────────────────
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─────────────────────────────────────────────────────────
# REST FRAMEWORK SOZLAMALARI
# ─────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "core.authentication.CsrfExemptSessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "uzyol.renderers.UnicodeJSONRenderer",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    # Throttling (Rate limiting) - brute force hujumiga qarshi
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",   # Anonim foydalanuvchilar: soatiga 100 ta so'rov
        "user": "1000/hour",  # Autentifikatsiya qilinganlar: soatiga 1000 ta
        "login": "10/hour",   # Login urinishlari: soatiga 10 ta
    },
}

# ─────────────────────────────────────────────────────────
# JWT TOKEN SOZLAMALARI
# ─────────────────────────────────────────────────────────
SIMPLE_JWT = {
    # Xavfsiz token muddatlari (avval 500 hafta edi - JUDA XAVFLI!)
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),       # 8 soat (1 ish kuni)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),       # 30 kun
    "ROTATE_REFRESH_TOKENS": True,     # Har yangilanishda yangi refresh token
    "BLACKLIST_AFTER_ROTATION": True,  # Eski tokenni qora ro'yxatga qo'shish
    "UPDATE_LAST_LOGIN": True,         # Oxirgi kirish vaqtini yangilash

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# ─────────────────────────────────────────────────────────
# SESSION SOZLAMALARI
# ─────────────────────────────────────────────────────────
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 soat (soniyalarda)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ─────────────────────────────────────────────────────────
# JAZZMIN ADMIN PANEL SOZLAMALARI
# ─────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "Oʻzyoʻlkoʻprik Admin",
    "site_header": "Oʻzyoʻlkoʻprik",
    "site_brand": "Oʻzyoʻlkoʻprik",
    "welcome_sign": "Oʻzyoʻlkoʻprik boshqaruv paneliga xush kelibsiz",
    "copyright": "Oʻzyoʻlkoʻprik AJ",
    "search_model": ["auth.User", "uzyol.CatalogItem"],
    "changeform_format_overrides": {
        "auth.user": "single",
    },

    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Saytga o'tish", "url": "http://127.0.0.1:3000", "new_window": True},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": [
        "uzyol.SiteSettings",
        "uzyol.NavigationItem",
        "uzyol.HomeContent",
        "uzyol.Page",
        "uzyol.CatalogItem",
        "uzyol.News",
        "uzyol.Leader",
        "uzyol.Announcement",
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "uzyol": "fas fa-road",
        "uzyol.SiteSettings": "fas fa-cogs",
        "uzyol.NavigationItem": "fas fa-compass",
        "uzyol.HomeContent": "fas fa-home",
        "uzyol.Page": "fas fa-file-alt",
        "uzyol.CatalogItem": "fas fa-folder-open",
        "uzyol.News": "fas fa-newspaper",
        "uzyol.Leader": "fas fa-user-tie",
        "uzyol.Announcement": "fas fa-bullhorn",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_link_size": "navbar-small",
    "sidebar_link_size": "sidebar-small",
    "sidebar_sidebar_link_size": "sidebar-small",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_layout": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}






