# Generated by Django 5.2.4 on 2026-08-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Каталог ver. 2.pdf', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='catalogs/')),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.CharField(blank=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='uzyol.page')),
            ],
            options={
                'verbose_name': 'katalog hujjati',
                'verbose_name_plural': 'katalog hujjatlari',
                'ordering': ('order', 'id'),
            },
        ),
    ]
