# Generated by Django 5.2.4 on 2026-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0004_catalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='embed_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
