# Generated by Django 5.2.4 on 2026-08-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0005_catalogitem_embed_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ('order', 'id'), 'verbose_name': "rahbariyat a'zosi", 'verbose_name_plural': 'rahbariyat'},
        ),
        migrations.AlterModelOptions(
            name='sitepayload',
            options={'verbose_name': 'sayt kontenti yuklamasi', 'verbose_name_plural': 'sayt kontenti yuklamalari'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='intro',
            field=models.TextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='uzyol.page', verbose_name='Sahifa'),
        ),
        migrations.AlterField(
            model_name='announcementitem',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='uzyol.announcement', verbose_name='Eʼlon'),
        ),
        migrations.AlterField(
            model_name='announcementitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='announcementitem',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Element matni'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=models.TextField(blank=True, verbose_name="Tavsif (Ta'rif)"),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='embed_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Koʻrish havolasi (Embed URL)'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='catalogs/', verbose_name='Hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='file_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Fayl hajmi'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='file_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Hujjat havolasi (Google Drive va h.k.)'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='uzyol.page', verbose_name='Sahifa'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='title',
            field=models.CharField(default='Каталог ver. 2.pdf', max_length=255, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='homecapability',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='uzyol.homecontent', verbose_name='Bosh sahifa kontenti'),
        ),
        migrations.AlterField(
            model_name='homecapability',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='homecapability',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Vazifa nomi'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='intro',
            field=models.TextField(verbose_name='Kirish matni'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='purpose',
            field=models.TextField(verbose_name='Maqsad va vazifalar'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='uzyol.homecontent', verbose_name='Bosh sahifa kontenti'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='text',
            field=models.TextField(verbose_name='Vazifa matni'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='born',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tugʻilgan yili va joyi'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='education',
            field=models.TextField(blank=True, verbose_name='Maʼlumoti'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=255, verbose_name='F.I.SH.'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Menyu nomi'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='uzyol.navigationitem', verbose_name='Ota menyu'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Batafsil matn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Rasm havolasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(verbose_name='Nashr qilingan vaqti'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Qisqacha mazmuni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='document',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.TextField(blank=True, verbose_name='Holat (Status)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sahifa sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('empty', 'Boʻsh sahifa'), ('status', 'Status sahifa'), ('leaders', 'Rahbariyat'), ('document', 'Hujjat'), ('announcement', 'Eʼlon'), ('contact', 'Qayta aloqa')], max_length=32, verbose_name='Sahifa turi'),
        ),
        migrations.AlterField(
            model_name='sitepayload',
            name='name',
            field=models.CharField(default='main', max_length=64, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sitepayload',
            name='payload',
            field=models.JSONField(verbose_name='Yuklama (Payload JSON)'),
        ),
        migrations.AlterField(
            model_name='sitepayload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bank',
            field=models.TextField(blank=True, verbose_name='Bank rekvizitlari'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Aloqa sahifasi rasmi havolasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Asosiy rasm havolasi (Hero Image)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Yuridik nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Logotip havolasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Xarita havolasi (Google/Yandex map)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Oʻzyoʻlkoʻprik', max_length=128, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=64, verbose_name='Asosiy telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=64, verbose_name='Qoʻshimcha telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='plant_image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Zavod rasmi havolasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Manba havolasi (Source URL)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.TextField(blank=True, verbose_name='Shior (Tagline)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
    ]
