# Generated by Django 5.2.4 on 2026-08-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0006_alter_leader_options_alter_sitepayload_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='source_url',
        ),
    ]
