# Generated by Django 5.2.4 on 2026-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0007_remove_sitesettings_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Asosiy rasm (Hero Image)'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, verbose_name='Slug (URL manzili)'),
        ),
    ]
