# Generated by Django 5.2.4 on 2026-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0008_sitesettings_hero_image_alter_navigationitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='navigation/', verbose_name='Orqa fon rasmi (Background Image)'),
        ),
    ]
