# Generated by Django 5.2.4 on 2026-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0009_navigationitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='capabilities_eyebrow',
            field=models.CharField(default='Yoʻnalishlar', max_length=128, verbose_name='Yoʻnalishlar ustki matni (Eyebrow)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='capabilities_title',
            field=models.CharField(default='Koʻprik infratuzilmasi uchun asosiy xizmat bloklari', max_length=255, verbose_name='Yoʻnalishlar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Asosiy rasm (Hero Image)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_tagline',
            field=models.TextField(blank=True, verbose_name='Shior (Tagline)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Asosiy sarlavha (Hero Title)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='model_eyebrow',
            field=models.CharField(default='Klaster Modeli', max_length=128, verbose_name='Klaster modeli ustki matni (Eyebrow)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='model_title',
            field=models.CharField(default='Loyihadan tayyor konstruksiyagacha yagona boshqaruv', max_length=255, verbose_name='Klaster modeli sarlavhasi'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='tasks_eyebrow',
            field=models.CharField(default='Vazifalar', max_length=128, verbose_name='Vazifalar ustki matni (Eyebrow)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='tasks_title',
            field=models.CharField(default='Klaster bajaradigan asosiy ishlar', max_length=255, verbose_name='Vazifalar sarlavhasi'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='workflow_eyebrow',
            field=models.CharField(default='Ish Oqimi', max_length=128, verbose_name='Ish oqimi ustki matni (Eyebrow)'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='workflow_title',
            field=models.CharField(default='Texnik qarordan amaliy natijagacha', max_length=255, verbose_name='Ish oqimi sarlavhasi'),
        ),
    ]
