# Generated by Django 5.2.4 on 2026-08-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0010_homecontent_capabilities_eyebrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='plant_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Zavod rasmi (Plant Image)'),
        ),
    ]
