# Generated by Django 5.2.4 on 2026-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0011_homecontent_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='plant_image',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='tasks_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Operatsion Vazifalar boʻlimi rasmi (Tasks Image)'),
        ),
    ]
