# Generated by Django 5.2.4 on 2026-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0012_remove_homecontent_plant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matn (Content)'),
        ),
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pages/', verbose_name='Fayl yuklash (File)'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Rasm yuklash (Image)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True, verbose_name='Slug (URL manzili)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('empty', 'Boʻsh sahifa'), ('status', 'Status sahifa'), ('leaders', 'Rahbariyat'), ('document', 'Hujjat'), ('announcement', 'Eʼlon'), ('contact', 'Qayta aloqa')], default='status', max_length=32, verbose_name='Sahifa turi'),
        ),
    ]
