# Generated by Django 5.2.4 on 2026-08-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0013_page_content_page_file_page_image_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshIshOrinlari',
            fields=[
            ],
            options={
                'verbose_name': 'Boʻsh ish oʻrinlari',
                'verbose_name_plural': 'Boʻsh ish oʻrinlari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.CreateModel(
            name='KorxonaUstavi',
            fields=[
            ],
            options={
                'verbose_name': 'Korxona ustavi',
                'verbose_name_plural': 'Korxona ustavi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.CreateModel(
            name='NarxNavo',
            fields=[
            ],
            options={
                'verbose_name': 'Narx-navo',
                'verbose_name_plural': 'Narx-navo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.CreateModel(
            name='QaytaAloqa',
            fields=[
            ],
            options={
                'verbose_name': 'Qayta aloqa',
                'verbose_name_plural': 'Qayta aloqa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.CreateModel(
            name='TashkiliyTuzilma',
            fields=[
            ],
            options={
                'verbose_name': 'Tashkiliy tuzilma',
                'verbose_name_plural': 'Tashkiliy tuzilma',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
    ]
