# Generated by Django 5.2.4 on 2026-08-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0014_boshishorinlari_korxonaustavi_narxnavo_qaytaaloqa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KatalogPage',
            fields=[
            ],
            options={
                'verbose_name': 'Katalog',
                'verbose_name_plural': 'Katalog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.CreateModel(
            name='NomenklaturaPage',
            fields=[
            ],
            options={
                'verbose_name': 'Nomenklatura',
                'verbose_name_plural': 'Nomenklatura',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
    ]
