# Generated by Django 5.2.4 on 2026-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0015_katalogpage_nomenklaturapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/', verbose_name='Rasm yuklash (Image)'),
        ),
    ]
