# Generated by Django 5.2.4 on 2026-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0016_leader_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarxNavoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('text', models.TextField(blank=True, verbose_name='Matn (tavsif)')),
                ('file', models.FileField(blank=True, null=True, upload_to='narx_navo/files/', verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='narx_navo/images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'narx-navo mahsuloti',
                'verbose_name_plural': 'narx-navo mahsulotlari',
                'ordering': ('order', 'id'),
            },
        ),
    ]
