# Generated by Django 5.2.4 on 2026-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0017_narxnavoproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshIshOrinlariProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ish o'rni nomi")),
                ('text', models.TextField(blank=True, verbose_name='Matn (tavsif)')),
                ('file', models.FileField(blank=True, null=True, upload_to='bosh_ish_orinlari/files/', verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bosh_ish_orinlari/images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "bo'sh ish o'rni",
                'verbose_name_plural': "bo'sh ish o'rinlari",
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ElonlarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="E'lon nomi")),
                ('text', models.TextField(blank=True, verbose_name='Matn (tavsif)')),
                ('file', models.FileField(blank=True, null=True, upload_to='elonlar/files/', verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, null=True, upload_to='elonlar/images/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': "e'lon",
                'verbose_name_plural': "e'lonlar",
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FiliallarPage',
            fields=[
            ],
            options={
                'verbose_name': 'Filiallar',
                'verbose_name_plural': 'Filiallar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('uzyol.page',),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('home', 'Bosh sahifa'), ('empty', 'Boʻsh sahifa'), ('status', 'Status sahifa'), ('leaders', 'Rahbariyat'), ('document', 'Hujjat'), ('announcement', 'Eʼlon'), ('contact', 'Qayta aloqa'), ('filiallar', 'Filiallar')], default='status', max_length=32, verbose_name='Sahifa turi'),
        ),
    ]
