# Generated by Django 5.2.4 on 2026-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0018_boshishorinlariproduct_elonlarproduct_filiallarpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Hudud (Viloyat)')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='Telefon raqami')),
                ('tasks', models.TextField(blank=True, verbose_name='Asosiy faoliyati (Vazifalari)')),
                ('status', models.CharField(default='Faol', max_length=64, verbose_name='Holati (Masalan: Faol, Asosiy bazasi)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='filiallar/images/', verbose_name='Rasm')),
                ('file', models.FileField(blank=True, null=True, upload_to='filiallar/files/', verbose_name='Fayl / Hujjat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ('order', 'id'),
            },
        ),
    ]
