# Generated by Django 5.2.4 on 2026-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0019_filialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialitem',
            name='description',
            field=models.TextField(blank=True, verbose_name="Filial haqida ma'lumot"),
        ),
        migrations.AddField(
            model_name='filialitem',
            name='director',
            field=models.CharField(blank=True, max_length=255, verbose_name='Filial rahbari (Direktor)'),
        ),
    ]
