# Generated by Django 5.2.4 on 2026-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzyol', '0020_filialitem_description_filialitem_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialitem',
            name='director_image',
            field=models.ImageField(blank=True, null=True, upload_to='filiallar/directors/', verbose_name='Direktor rasmi'),
        ),
        migrations.AlterField(
            model_name='filialitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='filiallar/images/', verbose_name='Filial rasmi'),
        ),
    ]
